---
# vars file for linux_post_install
DOMAIN: domain.lab
PRIMARYDNS: 10.0.60.100

#versão do satellite testada
satellite_server_version: 6

#pacotes para add
pkgs_add:
- pam-1.1.8-18.el7.i686
- perl
- python
- wget
- nscd
- nss-pam-ldapd
- vim

# pacotes a remover
pkgs_remove:
- telnet

#pacote de software especificos Satellite 5
pkgs_sat5:
- rhn-setup
- rhn-check
- rhn-client-tools
- labxml2
- jabberpy.noarch
- rhncfg-*
- rhn-check.noarch
- osad.noarch
- rhncfg-client
- rhncfg-client.noarch
- rhncfg-client.noarch
- rhn-setup.noarch

#pacote de software especificos sendmail
pkgs_sendmail:
- m4
- sendmail-cf

# parametros de hardening sysctl
hardening_sysctl:
- { name: kernel.randomize_va_space, value: 2 }
- { name: net.ipv6.conf.default.accept_ra, value: 0 }
- { name: net.ipv4.conf.all.secure_redirects, value: 0 }
- { name: net.ipv4.conf.all.send_redirects, value: 0 }
- { name: net.ipv4.conf.all.accept_redirects, value: 0 }
- { name: net.ipv4.conf.default.log_martians, value: 1 }
- { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
- { name: net.ipv4.icmp_ignore_bogus_error_responses, value: 1 }
- { name: net.ipv4.conf.default.rp_filter, value: 1 }
- { name: net.ipv4.tcp_syncookies, value: 1 }
- { name: net.ipv6.conf.default.accept_redirects, value: 0 }
- { name: net.ipv4.conf.default.send_redirects, value: 0 }
- { name: net.ipv4.conf.default.accept_redirects, value: 0 }
- { name: net.ipv4.conf.default.secure_redirects, value: 0 }
- { name: net.ipv4.conf.all.log_martians, value: 1 }
- { name: net.ipv4.conf.all.rp_filter, value: 1 }
- { name: net.ipv6.conf.all.accept_redirects, value: 0 }
- { name: net.ipv6.conf.default.accept_redirects, value: 0 }

permission_file:
- /var/log/boot.log
- /var/log/cron
- /var/log/spooler
- /var/log/secure
- /var/log/messages
