---
- name: Configuração Switch C3750
  hosts: all
  connection: local
  gather_facts: yes
  vars:
    - interface_switchport_protected:
    - vlan_switchport_protected:
    - description_switchport_protected:
    - interface_no_switchport_protected:
    - vlan_no_switchport_protected:
    - description_no_switchport_protected:
    - vlan_community_private_vlan:
    - vlan_community_private_vlan_association:
    - vlan_isolated_vlan:
    - vlan_isolated_vlan_association:
    - vlan_promisc:
  tasks:

  - name: executando show version no switch
    ios_command:
      commands: show version
    register: show_version

  - debug: var=show_version

  - name: Configuração com o Switchport protected
    ios_config:
      lines:
        - interface "{{ interface_switchport_protected }}"
        - descriptio "{{ vlan_switchport_protected }}"
        - switchport access vlan "{{ description_switchport_protected }}"
        - switchport mode access
        - switchport protected
        - switchport block multicast
        - switchport block unicast
        - load-interval 30
        - storm-control broadcast level 2.00
        - storm-control action trap
        - spanning-tree portfast
        - spanning-tree bpdufilter enable
        - speed auto
        - duplex auto
        - no shut
      
  - name: Configuração sem o Switchport protected
    ios_config:
      lines:
        - interface "{{ interface_no_switchport_protected }}"
        - description "{{ vlan_no_switchport_protected }}"
        - switchport access vlan "{{ description_no_switchport_protected }}"
        - switchport mode access
        - load-interval 30
        - storm-control broadcast level 2.00
        - storm-control action trap
        - spanning-tree portfast
        - spanning-tree bpdufilter enable
        - speed auto
        - duplex auto
        - no shut

#  - debug: msg="Configuração de Interface Community (Private VLan)"    
  - name: Configuração de Interface Community (Private VLan)
    ios_config:
      lines:
        - vlan "{{ vlan_community_private_vlan }}"
        - name pri-community-gerfw
        - private-vlan primary "{{ vlan_community_private_vlan_association }}"
        - vlan "{{ vlan_community_private_vlan_association }}"
        - name community1-gerfw
        - private-vlan community

#  - debug: msg="Configurando interface isolada"
  - name: Configuração de Interface isolada
    ios_config:
      lines:
        - vlan "{{ vlan_isolated_vlan }}"
        - name pri-isolated-redes
        - private-vlan primary
        - private-vlan association "{{ vlan_isolated_vlan_association }}"
        - vlan "{{ vlan_isolated_vlan_association }}"
        - name isolated-redes
        - private-vlan isolated

  - debug: msg="Configurando interface promiscua"
  - name: Configuração de Interface promiscua
    ios_config:
      lines:
        - vlan "{{ vlan_promisc }}"
        - name pri-promisc-geral
